#!/usr/bin/env ruby

def die_with_usage(err=nil, ecode=nil)
  name = File.basename($0)
  puts <<~EOS
    Usage: #{name} <number>

    Print a number with in human-readable form.

    -h, --help

      Print this help string.

  EOS
  if err
    ecode ||= 1
    puts "ERROR: #{err}"
  else
    ecode ||= 0
  end
  exit ecode
end

die_with_usage() if ARGV.size == 0

num = "#{ARGV[0]}"
if ['-h', '--help'].member?(num)
  die_with_usage()
end
unless num =~ /^[0-9\.]+$/
  die_with_usage("A number is required")
end

def group3(n)
  return n.to_s.
    split('').
    reverse.each_slice(3).
    map{|g| g.join.reverse }.
    reverse.join(',')
end

num.gsub!(/\.+/, '.')
num.gsub!(/[^0-9\.]/, '')
whole, deci = num.split('.')
puts group3(whole) + (deci ? ".#{deci}" : '')
