#!/usr/bin/env bash

usage() {
cat << EOF
Usage: $0 -d <database> [-p <port>]

This script forcefully disconnects all connections
on a particular database.

  -h, --help
    Display this help.
  -d  
    The name of the database.
  -p  
    The Postgres server port.
    Defaults to 5432.

EOF
}

DB_NAME=
DB_PORT=5432 # Default

if [ "$1" = "--help" ]; then
  usage
  exit 0
fi

while getopts "hd:p:" OPTION
do 
  case $OPTION in
    h)
      usage
      exit 0
      ;;
    d)
      DB_NAME=$OPTARG
      ;;
    p)
      DB_PORT=$OPTARG
      ;;
  esac
done

if [[ -z $DB_NAME ]] || [[ -z $DB_PORT ]]
then
  echo "[DEBUG] DB_NAME=$DB_NAME"
  echo "[DEBUG] DB_PORT=$DB_PORT"
  usage
  exit 1
fi

echo "DB_NAME=$DB_NAME"
echo "DB_PORT=$DB_PORT"


SQL="SELECT pg_terminate_backend(pg_stat_activity.pid) FROM pg_stat_activity WHERE pg_stat_activity.datname = '$DB_NAME' AND pid <> pg_backend_pid()"

printf "SQL=\"$SQL\"\n"

psql $DB_NAME -p $DB_PORT -c "$SQL"

