#!/usr/bin/env bash

DBNAME="$1"
NOWNER="$2"
for tbl in `psql -qAt -c "select tablename from pg_tables where schemaname = 'public';" $DBNAME` ; do  psql -c "alter table \"$tbl\" owner to $NOWNER" $DBNAME ; done
for tbl in `psql -qAt -c "select sequence_name from information_schema.sequences where sequence_schema = 'public';" $DBNAME` ; do  psql -c "alter table \"$tbl\" owner to $NOWNER" $DBNAME ; done
for tbl in `psql -qAt -c "select table_name from information_schema.views where table_schema = 'public';" $DBNAME` ; do  psql -c "alter table \"$tbl\" owner to $NOWNER" $DBNAME ; done
