#!/usr/bin/env perl

our %ips = ();

sub display() {
  system("clear");
  foreach my $ip (sort keys %ips) {
    print "$ip\n";
  }
}

open(my $prog, "tcpdump -nnl 2>&1 |") or die "execute failed";
while(my $line=<$prog>) {
  chomp $line;
  #print "LINE: $line\n";
  while($line =~ /(\d{1,4}\.\d{1,4}\.\d{1,4}\.\d{1,4})/g) {
    #print "IP_FOUND=$1\n";
    $ips{$1} = 1;
  }
  display();
}
close($prog);
